[package]
name = "GhostHealth-Guard"
version = "0.1.0"
edition = "2024"


[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
secrecy = { version = "0.8", features = ["serde"] }
serde_json = "1.0"
subtle = "2.4" # Essential for timing-attack-safe comparison